force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>The breed of the dog record</description>
    <label>Breed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>beagle</fullName>
            </value>
            <value>
                <fullName>boxer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes the adoption process for a pet</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>RegisteredAvailable</fullName>
                <label>Registered - Available</label>
            </value>
            <value>
                <fullName>InAdoptionProcess</fullName>
                <label>In Adoption Process</label>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/recordTypes/Dog.recordType-meta.xml
<RecordType>
    <fullName>Dog</fullName>
    <active>true</active>
    <description>Indicates a rescued dog registered in the Animal Shelter</description>
    <label>Dog</label>
</RecordType>

force-app/main/default/classes/PetTriggerHandlerTest.cls
@isTest
public with sharing class PetTriggerHandlerTest {
	@TestSetup
	static void testSetup(){
		Configuration__c endpoint = new Configuration__c (
			Name = 'DogAPIGetImageEndpoint',
			Value__c = 'https://dog.ceo/api/breed/$$$/images/random'
		);
		Configuration__c httpMethod = new Configuration__c (
			Name = 'DogAPIGetImageMethod',
			Value__c = 'GET'
		);
		insert new List<Configuration__c>{endpoint, httpMethod};
	}

	@isTest
	public static void testGetPictureSuccess() {
		Test.setMock(HttpCalloutMock.class, new TestMocks.getImagesSuccess());
		Pet__c testPet = new Pet__c(
			Name = 'test pet name',
			Status__c = Constants.PET_STATUS_CREATED,
			Breed__c = 'Boxer'
		);

		Test.startTest();
		insert testPet;
		Test.stopTest();

		testPet = [SELECT Id,
			PictureUrl__c,
			Status__c
			FROM Pet__c
			WHERE Id = :testPet.Id];

		Assert.isTrue(String.isNotBlank(testPet.PictureUrl__c), 'Dog Image is still blank');
		Assert.areEqual(testPet.Status__c, Constants.PET_STATUS_REGISTERED, 'Dog Status is not updated');
	}

	@isTest
	public static void testGetPictureFail() {
		Test.setMock(HttpCalloutMock.class, new TestMocks.getImagesFail());
		Pet__c testPet = new Pet__c(
			Name = 'test pet name',
			Status__c = Constants.PET_STATUS_CREATED,
			Breed__c = 'Boxer'
		);

		Test.startTest();
		insert testPet;
		Test.stopTest();

		testPet = [SELECT Id,
			PictureUrl__c,
			Status__c
			FROM Pet__c
			WHERE Id = :testPet.Id];

		Assert.isTrue(String.isBlank(testPet.PictureUrl__c), 'Dog Image is not blank');
		Assert.areEqual(testPet.Status__c, Constants.PET_STATUS_CREATED, 'Dog Status is not still Created');
	}
}