force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>The breed of the dog record</description>
    <label>Breed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>beagle</fullName>
            </value>
            <value>
                <fullName>boxer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Province of the current Pet location</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/recordTypes/Dog.recordType-meta.xml
<RecordType>
    <fullName>Dog</fullName>
    <active>true</active>
    <description>Indicates a rescued dog registered in the Animal Shelter</description>
    <label>Dog</label>
</RecordType>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Drenthe</fullName>
    </customValue>
    <customValue>
        <fullName>Flevoland</fullName>
    </customValue>
    <customValue>
        <fullName>Friesland</fullName>
    </customValue>
    <customValue>
        <fullName>Gelderland</fullName>
    </customValue>
    <customValue>
        <fullName>Groningen</fullName>
    </customValue>
    <customValue>
        <fullName>Limburg</fullName>
    </customValue>
    <customValue>
        <fullName>North Brabant</fullName>
    </customValue>
    <customValue>
        <fullName>North Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Overijssel</fullName>
    </customValue>
    <customValue>
        <fullName>South Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Utrecht</fullName>
    </customValue>
    <customValue>
        <fullName>Zeeland</fullName>
    </customValue>
    <description>List of dutch provinces</description>
    <masterLabel>Provinces</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PetFormControllerTest.cls
@isTest
public with sharing class PetFormControllerTest {
	@TestSetup
	static void testSetup(){
		Configuration__c endpoint = new Configuration__c (
			Name = 'DogAPIGetBreedsEndpoint',
			Value__c = 'testendpoint'
		);
		Configuration__c httpMethod = new Configuration__c (
			Name = 'DogAPIGetBreedsMethod',
			Value__c = 'GET'
		);
		insert new List<Configuration__c>{endpoint, httpMethod};
	}

	@isTest
	static void testGetDogRecordType() {
		Assert.areEqual(
			Schema.SObjectType.Pet__c.getRecordTypeInfosByName().get(Constants.PET_RT_NAME_DOG).getRecordTypeId(),
			PetFormController.getDogRecordTypeId(),
			'The returned RecordTypeId is not correct');
	}

	@isTest
	static void testInsertCompensationSuccess() {
		Pet__c pet = new Pet__c(
			Name = 'test dog name',
			Breed__c = 'boxer',
			Location__c = 'Limburg'
		);

		Test.startTest();
		Id petId = PetFormController.insertPet(pet);
		Test.stopTest();

		List<Pet__c> pets = [SELECT Id,
			Name,
			Breed__c,
			Location__c
			FROM Pet__c];

		Assert.isFalse(pets.isEmpty(), 'No Pet record has been created');
		Assert.areEqual(1, pets.size(), 'There is more than a Pet record');
		Assert.areEqual(pet.Id, pets[0].Id, 'Pet Id value is not set correctly');
		Assert.areEqual(pet.Name, pets[0].Name, 'Pet Name value is not set correctly');
		Assert.areEqual(pet.Breed__c, pets[0].Breed__c, 'Pet Breed__c value is not set correctly');
		Assert.areEqual(pet.Location__c, pets[0].Location__c, 'Pet Location__c value is not set correctly');
	}

	@isTest
	static void testInsertCompensationFail() {
		Boolean exceptionOccurred = false;

		Pet__c pet = new Pet__c(
			Location__c = 'XXXXX'
		);

		try {
			Test.startTest();
			Id petId = PetFormController.insertPet(pet);
			Test.stopTest();
		} catch (AuraHandledException ex) {
			exceptionOccurred = true;
		}

		Assert.isTrue(exceptionOccurred, 'No exception has occured');
	}

	@isTest
	static void testGetBreedSuccess() {
		Test.setMock(HttpCalloutMock.class, new TestMocks.getBreedsSuccess());

		Test.startTest();
		Set<String> response = (Set<String>) PetFormController.getDogBreeds();
		Test.stopTest();

		Assert.isTrue(!response.isEmpty(), 'No item returned');
		Assert.areEqual(2, response.size(), 'Results has not 2 items');
	}

	@isTest
	static void testGetBreedFail() {
		Test.setMock(HttpCalloutMock.class, new TestMocks.getBreedsFail());
		Boolean exceptionOccurred = false;

		try {
			Test.startTest();
			Set<String> response = (Set<String>) PetFormController.getDogBreeds();
			Test.stopTest();
		} catch (AuraHandledException ex) {
			exceptionOccurred = true;
		}

		Assert.isTrue(exceptionOccurred, 'No exception has occured');
	}
}