force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>The breed of the dog record</description>
    <label>Breed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>beagle</fullName>
            </value>
            <value>
                <fullName>boxer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes the adoption process for a pet</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>RegisteredAvailable</fullName>
                <label>Registered - Available</label>
            </value>
            <value>
                <fullName>InAdoptionProcess</fullName>
                <label>In Adoption Process</label>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/recordTypes/Dog.recordType-meta.xml
<RecordType>
    <fullName>Dog</fullName>
    <active>true</active>
    <description>Indicates a rescued dog registered in the Animal Shelter</description>
    <label>Dog</label>
</RecordType>

force-app/main/default/classes/BatchGetDogImage.cls
public with sharing class BatchGetDogImage implements Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts {
	Id dogRecordTypeId = Schema.SObjectType.Pet__c.getRecordTypeInfosByDeveloperName().get(Constants.PET_RT_NAME_DOG).getRecordTypeId();
	String endpoint = Configuration__c.getValues('DogAPIGetImageEndpoint').Value__c;
	String method = Configuration__c.getValues('DogAPIGetImageMethod').Value__c;
	String statusCreated = Constants.PET_STATUS_CREATED;
	Integer calloutsLimit = 50;

	public Database.QueryLocator start(Database.BatchableContext bc) {
		String query = 'SELECT Id, ' +
			'Breed__c ' +
			'FROM Pet__c ' +
			'WHERE RecordTypeId = :dogRecordTypeId ' +
			'AND Status__c = :statusCreated';

		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext bc, List<Pet__c> dogs) {
		for(Pet__c dog : dogs) {
			Http http = new Http();

			HttpRequest req = new HttpRequest();
			req.setEndpoint(endpoint.replace('$$$', dog.Breed__c));
			req.setMethod(method);

			HttpResponse res = http.send(req);

			Map<String,Object> responseBody = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());

			dog.PictureUrl__c = (String) responseBody.get('message');
			dog.Status__c = Constants.PET_STATUS_REGISTERED;
		}

		update dogs;
	}

	public void finish(Database.BatchableContext bc) {}

	public void execute(SchedulableContext context) {
		Database.executeBatch(new BatchGetDogImage(), calloutsLimit);
	}
}