force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Breed__c.field-meta.xml
<CustomField>
    <fullName>Breed__c</fullName>
    <description>The breed of the dog record</description>
    <label>Breed</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>beagle</fullName>
            </value>
            <value>
                <fullName>boxer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes the adoption process for a pet</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>RegisteredAvailable</fullName>
                <label>Registered - Available</label>
            </value>
            <value>
                <fullName>InAdoptionProcess</fullName>
                <label>In Adoption Process</label>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/recordTypes/Dog.recordType-meta.xml
<RecordType>
    <fullName>Dog</fullName>
    <active>true</active>
    <description>Indicates a rescued dog registered in the Animal Shelter</description>
    <label>Dog</label>
</RecordType>

force-app/main/default/classes/BatchGetDogImageTest.cls
@isTest
public with sharing class BatchGetDogImageTest {

	@TestSetup
	static void testSetup(){
		Id dogRecordTypeId = Schema.SObjectType.Pet__c.getRecordTypeInfosByDeveloperName().get(Constants.PET_RT_NAME_DOG).getRecordTypeId();

		Configuration__c endpoint = new Configuration__c (
			Name = 'DogAPIGetImageEndpoint',
			Value__c = 'https://dog.ceo/api/breed/$$$/images/random'
		);
		Configuration__c httpMethod = new Configuration__c (
			Name = 'DogAPIGetImageMethod',
			Value__c = 'GET'
		);
		insert new List<Configuration__c>{endpoint, httpMethod};

		Pet__c testPet1 = new Pet__c(
			Name = 'test pet1 name',
			RecordTypeId = dogRecordTypeId,
			Status__c = Constants.PET_STATUS_CREATED,
			Breed__c = 'Boxer'
		);
		Pet__c testPet2 = new Pet__c(
			Name = 'test pet2 name',
			RecordTypeId = dogRecordTypeId,
			Status__c = Constants.PET_STATUS_CREATED,
			Breed__c = 'Boxer'
		);
		Pet__c testPet3 = new Pet__c(
			Name = 'test pet3 name',
			RecordTypeId = dogRecordTypeId,
			Status__c = Constants.PET_STATUS_CREATED,
			Breed__c = 'Pug'
		);
		Pet__c testPet4 = new Pet__c(
			Name = 'test pet4 name',
			RecordTypeId = dogRecordTypeId,
			Status__c = Constants.PET_STATUS_REGISTERED,
			Breed__c = 'Boxer'
		);
		insert new List<Pet__c>{testPet1, testPet2, testPet3, testPet4};
	}

	@isTest
	public static void testSetDogImageSuccess() {
		Test.setMock(HttpCalloutMock.class, new TestMocks.getImagesSuccess());
		List<Pet__c> createdDogs = [SELECT Id
			FROM Pet__c
			WHERE Status__c = :Constants.PET_STATUS_CREATED];

		Assert.isFalse(createdDogs.isEmpty(), 'There is no dogs in created status');

		Test.startTest();
		Database.executeBatch(new BatchGetDogImage(), 50);
		Test.stopTest();

		List<Pet__c> registeredDogs = [SELECT Id,
			PictureUrl__c,
			Name
			FROM Pet__c
			WHERE Id IN :createdDogs];

		createdDogs = [SELECT Id
			FROM Pet__c
			WHERE Status__c = :Constants.PET_STATUS_CREATED];

		Assert.isTrue(createdDogs.isEmpty(), createdDogs.size() + ' Dogs are still in Created status');
		Assert.isFalse(registeredDogs.isEmpty(), 'No Registered Dogs found');
		for(Pet__c dog : registeredDogs) {
			Assert.isTrue(String.isNotBlank(dog.PictureUrl__c), 'The registered dog ' + dog.Name + ' did not receive an Image');
		}
	}
}