force-app/main/default/objects/AdoptionRequest__c/AdoptionRequest__c.object-meta.xml
<CustomObject>
    <description>Join object between a Pet and an Account</description>
    <label>Adoption Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Adoption Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoption Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AdoptionRequest__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Adoption Requests</relationshipLabel>
    <relationshipName>AdoptionRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AdoptionRequest__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <description>Pet that the adoption refers to</description>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoption Requests</relationshipLabel>
    <relationshipName>AdoptionRequests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AdoptionRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Adoption Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CompletedAdopted</fullName>
                <label>Completed - Adopted</label>
            </value>
            <value>
                <fullName>CompletedNotAdopted</fullName>
                <label>Completed - Not Adopted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes the adoption process for a pet</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>RegisteredAvailable</fullName>
                <label>Registered - Available</label>
            </value>
            <value>
                <fullName>InAdoptionProcess</fullName>
                <label>In Adoption Process</label>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdoptionRequestTriggerHandler.cls
public with sharing class AdoptionRequestTriggerHandler {
	private static Set<String> inProgressStatuses = new Set<String>{
		Constants.REQUEST_STATUS_CREATED,
		Constants.REQUEST_STATUS_APPROVED
	};

	public static void setPetStatus(List<AdoptionRequest__c> requests) {
		List<Pet__c> toUpdate = new List<Pet__c>();

		List<AdoptionRequest__c> successfullRequests = Utils.filter(requests, 'Status__c', Constants.REQUEST_STATUS_ADOPTED, true);
		List<AdoptionRequest__c> unsuccessfullRequests = Utils.filter(requests, 'Status__c', Constants.REQUEST_STATUS_NOT_ADOPTED, true);
		List<AdoptionRequest__c> inProgressRequests = Utils.filter(requests, 'Status__c', inProgressStatuses, true);

		List<Case> casesToClose = [SELECT Id
			FROM Case
			WHERE Id IN :Utils.getSet(successfullRequests, 'Case__c')];

		for(AdoptionRequest__c request : successfullRequests) {
			toUpdate.add(new Pet__c(
				Id = request.Pet__c,
				Status__c = Constants.PET_STATUS_ADOPTED));
		}
		for(AdoptionRequest__c request : unsuccessfullRequests) {
			toUpdate.add(new Pet__c(
				Id = request.Pet__c,
				Status__c = Constants.PET_STATUS_REGISTERED));
		}
		for(AdoptionRequest__c request : inProgressRequests) {
			toUpdate.add(new Pet__c(
				Id = request.Pet__c,
				Status__c = Constants.PET_STATUS_IN_ADOPTION));
		}
		for(Case c : casesToClose) {
			c.Status = Constants.CASE_STATUS_CLOSED;
		}

		if(!toUpdate.isEmpty()) update toUpdate;
		if(!casesToClose.isEmpty()) update casesToClose;
	}
}