force-app/main/default/objects/AdoptionRequest__c/AdoptionRequest__c.object-meta.xml
<CustomObject>
    <description>Join object between a Pet and an Account</description>
    <label>Adoption Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Adoption Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoption Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AdoptionRequest__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <description>Pet that the adoption refers to</description>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoption Requests</relationshipLabel>
    <relationshipName>AdoptionRequests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Province of the current Pet location</description>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pet__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>ImageUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Drenthe</fullName>
    </customValue>
    <customValue>
        <fullName>Flevoland</fullName>
    </customValue>
    <customValue>
        <fullName>Friesland</fullName>
    </customValue>
    <customValue>
        <fullName>Gelderland</fullName>
    </customValue>
    <customValue>
        <fullName>Groningen</fullName>
    </customValue>
    <customValue>
        <fullName>Limburg</fullName>
    </customValue>
    <customValue>
        <fullName>North Brabant</fullName>
    </customValue>
    <customValue>
        <fullName>North Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Overijssel</fullName>
    </customValue>
    <customValue>
        <fullName>South Holland</fullName>
    </customValue>
    <customValue>
        <fullName>Utrecht</fullName>
    </customValue>
    <customValue>
        <fullName>Zeeland</fullName>
    </customValue>
    <description>List of dutch provinces</description>
    <masterLabel>Provinces</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AdoptionFormController.cls
public with sharing class AdoptionFormController {
	@AuraEnabled
	public static List<Pet__c> searchPets(List<String> filters){
		Configuration__c pageSize = Configuration__c.getValues('AdoptionFormResultPageSize');
		String query = 'SELECT Id,' +
			'Name, ' +
			'PictureUrl__c, ' +
			'Location__c ' +
			'FROM Pet__c ';

		if(!filters.isEmpty()) {query += 'WHERE ' + String.join(filters, ' AND ');}
		query += ' LIMIT ' + Integer.valueOf(pageSize.Value__c);

		try {
			return Database.query(query);
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	@AuraEnabled
	public static String insertRequest(SObject record){
		try {
			insert (AdoptionRequest__c) record;
			return record.Id;
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}
}