force-app/main/default/objects/AdoptionRequest__c/AdoptionRequest__c.object-meta.xml
<CustomObject>
    <description>Join object between a Pet and an Account</description>
    <label>Adoption Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Adoption Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adoption Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AdoptionRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Account that performs the request</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Adoption Requests</relationshipLabel>
    <relationshipName>AdoptionRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AdoptionRequest__c/fields/Pet__c.field-meta.xml
<CustomField>
    <fullName>Pet__c</fullName>
    <description>Pet that the adoption refers to</description>
    <label>Pet</label>
    <referenceTo>Pet__c</referenceTo>
    <relationshipLabel>Adoption Requests</relationshipLabel>
    <relationshipName>AdoptionRequests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AdoptionRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Adoption Process</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>CompletedAdopted</fullName>
                <label>Completed - Adopted</label>
            </value>
            <value>
                <fullName>CompletedNotAdopted</fullName>
                <label>Completed - Not Adopted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Store key-value pairs</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/default/objects/Pet__c/Pet__c.object-meta.xml
<CustomObject>
    <description>It represents a rescued animal that is registered at the Animal Shelter</description>
    <label>Pet</label>
    <nameField>
        <label>Pet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pet__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Describes the adoption process for a pet</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>RegisteredAvailable</fullName>
                <label>Registered - Available</label>
            </value>
            <value>
                <fullName>InAdoptionProcess</fullName>
                <label>In Adoption Process</label>
            </value>
            <value>
                <fullName>Adopted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdoptionRequestTriggerHandlerTest.cls
@isTest
public with sharing class AdoptionRequestTriggerHandlerTest {
	@TestSetup
	static void testSetup(){
		insert new Configuration__c (
			Name = 'DisableSetImageInTrigger',
			Value__c = 'true'
		);
	}

	@isTest
	public static void testPetStatusUpdate() {
		Account testAccount = new Account(
			LastName = 'name test'
		);
		insert testAccount;

		Pet__c testPet1 = new Pet__c(
			Name = 'test pet1 name',
			Status__c = Constants.PET_STATUS_REGISTERED
		);
		Pet__c testPet2 = new Pet__c(
			Name = 'test pet2 name',
			Status__c = Constants.PET_STATUS_REGISTERED
		);
		insert new List<Pet__c>{testPet1, testPet2};

		AdoptionRequest__c request1 = new AdoptionRequest__c(
			Account__c = testAccount.Id,
			Pet__c = testPet1.Id,
			Status__c = Constants.REQUEST_STATUS_CREATED
		);
		AdoptionRequest__c request2 = new AdoptionRequest__c(
			Account__c = testAccount.Id,
			Pet__c = testPet2.Id,
			Status__c = Constants.REQUEST_STATUS_APPROVED
		);

		Test.startTest();
		insert new List<AdoptionRequest__c>{request1, request2};
		Test.stopTest();

		Set<Id> petIds = new Set<Id>{testPet1.Id, testPet2.Id};
		List<Pet__c> pets = [SELECT Id,
			Status__c
			FROM Pet__c
			WHERE Id IN :petIds];

		for(Pet__c pet : pets) {
			Assert.areEqual(Constants.PET_STATUS_IN_ADOPTION, pet.Status__c, 'Pet Status__c is not updated correctly');
		}
	}

	@isTest
	public static void testPetStatusUpdateOnUpdate() {
		Account testAccount = new Account(
			LastName = 'name test'
		);
		insert testAccount;

		Pet__c testPet1 = new Pet__c(
			Name = 'test pet1 name',
			Status__c = Constants.PET_STATUS_REGISTERED
		);
		Pet__c testPet2 = new Pet__c(
			Name = 'test pet2 name',
			Status__c = Constants.PET_STATUS_REGISTERED
		);
		insert new List<Pet__c>{testPet1, testPet2};

		AdoptionRequest__c request1 = new AdoptionRequest__c(
			Account__c = testAccount.Id,
			Pet__c = testPet1.Id,
			Status__c = Constants.REQUEST_STATUS_CREATED
		);
		AdoptionRequest__c request2 = new AdoptionRequest__c(
			Account__c = testAccount.Id,
			Pet__c = testPet2.Id,
			Status__c = Constants.REQUEST_STATUS_APPROVED
		);
		insert new List<AdoptionRequest__c>{request1, request2};

		request1.Status__c = Constants.REQUEST_STATUS_ADOPTED;
		request2.Status__c = Constants.REQUEST_STATUS_NOT_ADOPTED;

		Test.startTest();
		update new List<AdoptionRequest__c>{request1, request2};
		Test.stopTest();

		Set<Id> petIds = new Set<Id>{testPet1.Id, testPet2.Id};
		Map<Id, Pet__c> pets = new Map<Id,Pet__c>([SELECT Id,
			Status__c
			FROM Pet__c
			WHERE Id IN :petIds]);

		Assert.areEqual(Constants.PET_STATUS_ADOPTED, pets.get(request1.Pet__c).Status__c, 'Pet1 Status__c is not updated correctly');
		Assert.areEqual(Constants.PET_STATUS_REGISTERED, pets.get(request2.Pet__c).Status__c, 'Pet2 Status__c is not updated correctly');
	}
}